/**
 * Error codes từ backend API
 * Sync với: aurora-backend/src/main/java/com/aurora/backend/enums/ErrorCode.java
 */

export const ErrorCodes = {
  // User errors
  UNCATEGORIZED_EXCEPTION: 9999,
  INVALID_KEY: 1001,
  USER_EXISTED: 1002,
  USER_NOT_EXISTED: 1003,
  UNAUTHENTICATED: 1004, // 401 - Token invalid/expired
  UNAUTHORIZED: 1005, // 403 - No permission
  USERNAME_INVALID: 1006,
  INVALID_PASSWORD: 1007,
  USER_UPDATE_FAILED: 1008,
  USER_DELETE_FAILED: 1009,
  USERNAME_REQUIRED: 1010,
  PASSWORD_REQUIRED: 1011,
  FIRSTNAME_REQUIRED: 1012,
  LASTNAME_REQUIRED: 1013,
  DOB_INVALID: 1014,
  ACCOUNT_LOCKED: 1015,
  WEAK_PASSWORD: 1016,

  // Amenity errors
  AMENITY_EXISTED: 1100,
  AMENITY_NOT_EXISTED: 1101,
  AMENITY_NAME_REQUIRED: 1102,
  AMENITY_TYPE_REQUIRED: 1103,

  // Facility errors
  FACILITY_EXISTED: 1200,
  FACILITY_NOT_EXISTED: 1201,
  FACILITY_NAME_REQUIRED: 1202,
  HOTEL_ID_REQUIRED: 1203,
  HOTEL_NOT_EXISTED: 1204,

  // Booking errors
  BOOKING_NOT_EXISTED: 1300,
  BOOKING_DATE_INVALID: 1301,
  BOOKING_DATE_REQUIRED: 1302,
  BOOKING_CODE_REQUIRED: 1303,
  CUSTOMER_ID_REQUIRED: 1304,
  CHECKIN_DATE_FUTURE: 1305,
  CHECKOUT_DATE_FUTURE: 1306,
  BOOKING_CODE_EXISTED: 1307,
  INVALID_BOOKING_TOTAL: 1308,
  PRICE_MISMATCH: 1309,
  NO_ROOMS_AVAILABLE: 1310,
  EXCEEDS_ROOM_CAPACITY: 1311,

  // BookingRoom errors
  BOOKING_ROOM_NOT_EXISTED: 1400,
  BOOKING_ID_REQUIRED: 1401,
  ROOM_ID_REQUIRED: 1402,
  PRICE_REQUIRED: 1404,
  PRICE_POSITIVE: 1405,
  NIGHTS_REQUIRED: 1406,
  NIGHTS_POSITIVE: 1407,
  BOOKING_ROOM_EXISTED: 1408,

  // Hotel errors
  HOTEL_EXISTED: 1500,
  HOTEL_NAME_REQUIRED: 1501,
  HOTEL_CODE_REQUIRED: 1502,
  HOTEL_ADDRESS_REQUIRED: 1503,
  PHONE_INVALID: 1504,
  TIME_FORMAT_INVALID: 1505,

  // Payment errors
  PAYMENT_NOT_EXISTED: 1600,
  PAYMENT_METHOD_REQUIRED: 1601,
  PAYMENT_STATUS_REQUIRED: 1602,
  PAYMENT_AMOUNT_REQUIRED: 1603,
  PAYMENT_AMOUNT_POSITIVE: 1604,
  INVALID_PAYMENT_AMOUNT: 1605,
  PAYMENT_EXCEEDS_TOTAL: 1606,

  // Role errors
  ROLE_NOT_EXISTED: 1700,
  ROLE_EXISTED: 1701,
  ROLE_NAME_REQUIRED: 1702,

  // Permission errors
  PERMISSION_NOT_EXISTED: 1800,
  PERMISSION_EXISTED: 1801,
  PERMISSION_CODE_REQUIRED: 1802,

  // Promotion errors
  PROMOTION_NOT_EXISTED: 1900,
  PROMOTION_EXISTED: 1901,
  PROMOTION_CODE_REQUIRED: 1902,
  PROMOTION_NAME_REQUIRED: 1903,
  PROMOTION_DATE_INVALID: 1904,
  DISCOUNT_REQUIRED: 1905,
  DISCOUNT_POSITIVE: 1906,
  START_DATE_REQUIRED: 1907,
  END_DATE_REQUIRED: 1908,

  // RoomType errors
  ROOM_TYPE_NOT_EXISTED: 2000,
  ROOM_TYPE_EXISTED: 2001,
  ROOM_TYPE_NAME_REQUIRED: 2002,
  CAPACITY_ADULTS_REQUIRED: 2003,
  CAPACITY_ADULTS_POSITIVE: 2004,
  CAPACITY_CHILDREN_POSITIVE: 2005,
  SIZE_POSITIVE: 2006,

  // Room errors
  ROOM_NOT_FOUND: 2100,
  ROOM_NUMBER_ALREADY_EXISTS: 2101,
  ROOM_NUMBER_REQUIRED: 2102,
  ROOM_TYPE_ID_REQUIRED: 2103,
  FLOOR_POSITIVE: 2104,
  ROOM_TYPE_HOTEL_MISMATCH: 2105,
  HOTEL_NOT_FOUND: 2106,
  ROOM_TYPE_NOT_FOUND: 2107,

  // Service errors
  SERVICE_NOT_FOUND: 2200,
  SERVICE_EXISTED: 2201,
  SERVICE_NAME_REQUIRED: 2202,
  BASE_PRICE_POSITIVE: 2203,

  // ServiceBooking errors
  SERVICE_BOOKING_NOT_FOUND: 2300,
  SERVICE_BOOKING_EXISTED: 2301,
  SERVICE_ID_REQUIRED: 2302,
  DATETIME_REQUIRED: 2303,
  QUANTITY_POSITIVE: 2304,
  BOOKING_NOT_FOUND: 2305,
  USER_NOT_FOUND: 2306,

  // Branch errors
  BRANCH_NOT_EXISTED: 2400,
  BRANCH_CODE_EXISTED: 2401,
  BRANCH_NAME_REQUIRED: 2402,
  BRANCH_CODE_REQUIRED: 2403,
  BRANCH_ADDRESS_REQUIRED: 2404,
  BRANCH_HAS_ROOMS: 2405,
  USER_NOT_MANAGER: 2406,
  BRANCH_CITY_REQUIRED: 2407,
  BRANCH_DISTRICT_REQUIRED: 2408,
  BRANCH_WARD_REQUIRED: 2409,
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Error code names as strings (for comparing with API response)
 */
export const ErrorCodeNames = {
  UNCATEGORIZED_EXCEPTION: "UNCATEGORIZED_EXCEPTION",
  INVALID_KEY: "INVALID_KEY",
  USER_EXISTED: "USER_EXISTED",
  USER_NOT_EXISTED: "USER_NOT_EXISTED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  USERNAME_INVALID: "USERNAME_INVALID",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USERNAME_REQUIRED: "USERNAME_REQUIRED",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  FIRSTNAME_REQUIRED: "FIRSTNAME_REQUIRED",
  LASTNAME_REQUIRED: "LASTNAME_REQUIRED",
  DOB_INVALID: "DOB_INVALID",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  AMENITY_EXISTED: "AMENITY_EXISTED",
  AMENITY_NOT_EXISTED: "AMENITY_NOT_EXISTED",
  AMENITY_NAME_REQUIRED: "AMENITY_NAME_REQUIRED",
  AMENITY_TYPE_REQUIRED: "AMENITY_TYPE_REQUIRED",
  FACILITY_EXISTED: "FACILITY_EXISTED",
  FACILITY_NOT_EXISTED: "FACILITY_NOT_EXISTED",
  FACILITY_NAME_REQUIRED: "FACILITY_NAME_REQUIRED",
  HOTEL_ID_REQUIRED: "HOTEL_ID_REQUIRED",
  HOTEL_NOT_EXISTED: "HOTEL_NOT_EXISTED",
  BOOKING_NOT_EXISTED: "BOOKING_NOT_EXISTED",
  BOOKING_DATE_INVALID: "BOOKING_DATE_INVALID",
  BOOKING_DATE_REQUIRED: "BOOKING_DATE_REQUIRED",
  BOOKING_CODE_REQUIRED: "BOOKING_CODE_REQUIRED",
  CUSTOMER_ID_REQUIRED: "CUSTOMER_ID_REQUIRED",
  CHECKIN_DATE_FUTURE: "CHECKIN_DATE_FUTURE",
  CHECKOUT_DATE_FUTURE: "CHECKOUT_DATE_FUTURE",
  BOOKING_CODE_EXISTED: "BOOKING_CODE_EXISTED",
  INVALID_BOOKING_TOTAL: "INVALID_BOOKING_TOTAL",
  PRICE_MISMATCH: "PRICE_MISMATCH",
  NO_ROOMS_AVAILABLE: "NO_ROOMS_AVAILABLE",
  EXCEEDS_ROOM_CAPACITY: "EXCEEDS_ROOM_CAPACITY",
  // ... more if needed
} as const;

export type ErrorCodeName = (typeof ErrorCodeNames)[keyof typeof ErrorCodeNames];

